### ISSUE TITLE
perte des info consommation eau ESP

### ISSUE THREAD

**Issue by Martial-P** [PAPAMICA/home-config#1]
Bonjour, y a t il un moyen de ne plus perdre la consommation du jour et de la veille lors des mise à jour EspHome.  Merci par avance.

**Comment by PAPAMICA** [comment]
Bonjour @Martial-P,

J'utilise un compteur Home Assistant pour garder les données en base de données : 
![Paramètres – Home Assistant_2023-10-19_14 02 13](https://github.com/PAPAMICA/home-config/assets/29079741/eb77335d-7383-4ae3-b66b-2f92d55d7d3a)

N'hésitez pas si vous avez besoin de plus de renseignements.
